version: 2

jobs:
  lint:
    working_directory: ~/eslint-config-henribeck
    docker:
      - image: circleci/node:8@sha256:5f9ca557192333eb5614dfc7826477b4baa58eb4064a2f8a6910b80c2d55fffe
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run lint

  find-unused-rules:
    working_directory: ~/eslint-config-henribeck
    docker:
      - image: circleci/node:8@sha256:5f9ca557192333eb5614dfc7826477b4baa58eb4064a2f8a6910b80c2d55fffe
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Find unused rules
          command: yarn run find-unused-rules

workflows:
  version: 2

  test:
    jobs:
      - lint
      - find-unused-rules