version: 2

jobs:
  lint:
    working_directory: ~/eslint-config-henribeck
    docker:
      - image: circleci/node:8@sha256:844d7ccbba6a41d7b804f20d703229a34f91a6c98a1b160bece9cba54d3ae134
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run lint

  find-unused-rules:
    working_directory: ~/eslint-config-henribeck
    docker:
      - image: circleci/node:8@sha256:844d7ccbba6a41d7b804f20d703229a34f91a6c98a1b160bece9cba54d3ae134
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Find unused rules
          command: yarn run find-unused-rules

workflows:
  version: 2

  test:
    jobs:
      - lint
      - find-unused-rules