version: 2

jobs:
  lint:
    working_directory: ~/eslint-config-henribeck
    docker:
      - image: circleci/node:8@sha256:744c0829877ab7f73473d0553f1df84efc9d50f4cdc1cd256a4b0c271834b40d
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run lint

  find-unused-rules:
    working_directory: ~/eslint-config-henribeck
    docker:
      - image: circleci/node:8@sha256:744c0829877ab7f73473d0553f1df84efc9d50f4cdc1cd256a4b0c271834b40d
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Find unused rules
          command: yarn run find-unused-rules

workflows:
  version: 2

  test:
    jobs:
      - lint
      - find-unused-rules