version: 2

jobs:
  update-lockfile:
    working_directory: ~/eslint-config-henribeck
    docker:
      - image: circleci/node:8@sha256:a629192e19e872866a038cb56cc81bf7d43a0e01915e97c190e4ab9ab9dfa200
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Update lockfile
          command: ./node_modules/.bin/greenkeeper-lockfile-update
      - run:
          name: Upload lockfile
          command: ./node_modules/.bin/greenkeeper-lockfile-upload

  lint:
    working_directory: ~/eslint-config-henribeck
    docker:
      - image: circleci/node:8@sha256:a629192e19e872866a038cb56cc81bf7d43a0e01915e97c190e4ab9ab9dfa200
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run lint

  find-unused-rules:
    working_directory: ~/eslint-config-henribeck
    docker:
      - image: circleci/node:8@sha256:a629192e19e872866a038cb56cc81bf7d43a0e01915e97c190e4ab9ab9dfa200
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Find unused rules
          command: yarn run find-unused-rules

workflows:
  version: 2

  greenkeeper:
    jobs:
      - update-lockfile

  test:
    jobs:
      - lint
      - find-unused-rules