version: 2

jobs:
  lint:
    working_directory: ~/eslint-config-henribeck
    docker:
      - image: circleci/node:8@sha256:c68eaca5d57a539af8c4ef8fe271e74717917e04d3e93408e567568c09600888
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run lint

  find-unused-rules:
    working_directory: ~/eslint-config-henribeck
    docker:
      - image: circleci/node:8@sha256:c68eaca5d57a539af8c4ef8fe271e74717917e04d3e93408e567568c09600888
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Find unused rules
          command: yarn run find-unused-rules

workflows:
  version: 2

  test:
    jobs:
      - lint
      - find-unused-rules